In [15]:
import numpy as np
arr = np.array([[[1,2],[2,3],[4,5],[7,8]]])
arr.strides

(32, 8, 4)

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr1 = np.arange(10).reshape(2,5)
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
import numpy as np
np.random.seed(15)
np.random.randint(100)

72

In [6]:
cric_data = np.loadtxt("new.tsv", skiprows=1)
cric_data.shape

(15, 4)

In [10]:
file=np.loadtxt("new.tsv",skiprows=1)
file

array([[  0., 100.,  78., 342.],
       [  1.,  11.,  62., 191.],
       [  2.,   8.,  85., 252.],
       [  3.,  71.,  24., 307.],
       [  4., 104.,  17., 229.],
       [  5.,  18., 104., 246.],
       [  6.,   8.,  76., 226.],
       [  7.,  86.,  74., 288.],
       [  8.,  12.,  60., 216.],
       [  9.,  25.,  90., 304.],
       [ 10.,  56.,   6., 272.],
       [ 11.,  88.,  69., 302.],
       [ 12., 147.,  65., 312.],
       [ 13., 121., 146., 370.],
       [ 15.,  99., 110., 362.]])

In [16]:
sachin = np.zeros(15)

for i in range(15):
    sachin[i] = cric_data[i][1]
sachin

array([100.,  11.,   8.,  71., 104.,  18.,   8.,  86.,  12.,  25.,  56.,
        88., 147., 121.,  99.])