In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import  numpy as np

In [9]:
arr = np.array([[1,2,3,4],[5,6,7]],dtype=object)
arr

array([list([1, 2, 3, 4]), list([5, 6, 7])], dtype=object)

In [16]:
from numpy import random
x=random.rand()
print(x)

0.4542748475221734


In [18]:
x=random.randint(111)
print(x)

76


In [23]:
x=random.randint(100,size=(3))
print(x)

[97 21 75]


In [24]:
x=random.randint(100,size=(3,5))
print(x)

[[13 37 25 24  0]
 [23 71  8 63 24]
 [17 24  7 91 70]]


In [27]:
in_arr=np.array([8])
print("input array is",in_arr)
out_scalar= in_arr.item()
print("output scalar from input array",out_scalar)

input array is [8]
output scalar from input array 8


In [39]:
list1=[1,2,3]
list2=[[10],[20],[30]]
vector1=np.array(list1)
vector2=np.array(list2)
print(vector1)
print(vector2)

vertical vector
[1 2 3]
[[10]
 [20]
 [30]]


In [53]:
a=np.matrix('1 2;3 4')
print("via string input: \n" , a, "\n")
b=np.matrix([[5,6,7] , [4,6,8]],dtype=object)
print("via array-like input :\n",b)

via string input: 
 [[1 2]
 [3 4]] 

via array-like input :
 [[5 6 7]
 [4 6 8]]


In [73]:
A=[[6,7],
  [1,3]]

B=[[6,7],
  [1,3]]
print(np.dot(A,B))

[[43 63]
 [ 9 16]]


In [77]:
arr = np.array([[-1,23,78],[98,60,75],[79,25,10000]])
print(arr)

print(np.amin(arr))
print(np.amax(arr))

[[   -1    23    78]
 [   98    60    75]
 [   79    25 10000]]
-1
10000


In [81]:
a=np.array([9,6,7])
print(a)
print("mean of array a=",np.mean(a))
print("median of array a =",np.median(a))
print("standard deviation of array a=",np.std(a))
print("Variance of array a=",np.var(a))

[9 6 7]
mean of array a= 7.333333333333333
median of array a = 7.0
standard deviation of array a= 1.247219128924647
Variance of array a= 1.5555555555555554


In [93]:
data=[32,324,35,45,223,5,425,245,435,6,254,634,64,36,46,34,654,6,34,643,67,68763,45,46]
Q1=np.median(data[:10])
Q2=np.median(data[10:])
print(Q1)
print(Q2)

IQR = Q1-Q2
print(IQR)

134.0
55.0
79.0


In [99]:
a=np.array([2.12,3,5,5])
b=np.array([5,5,3,6])
c=a*b
print(c)

[10.6 15.  15.  30. ]
