In [3]:
import pandas as pd
arr=['p','r','s','q','t']
s1=pd.Series(arr)
s1

0    p
1    r
2    s
3    q
4    t
dtype: object

In [5]:
type(s1)

pandas.core.series.Series

In [7]:
s1[0],s1[1]

('p', 'r')

In [11]:
order=[1,2,3,3,3]
s2=pd.Series(arr,index=order)
s2

1    p
2    r
3    s
3    q
3    t
dtype: object

In [12]:
s2[3]

3    s
3    q
3    t
dtype: object

In [16]:
names = ["Akshit" , "Madhav", "Kedar" ,"Ajay" ,"Vaibhav"]
s3=pd.Series(arr , index = names)
s3

Akshit     p
Madhav     r
Kedar      s
Ajay       q
Vaibhav    t
dtype: object

In [18]:

s3=pd.Series(["Akshit" , "Madhav", "Kedar" ,"Ajay" ,"Vaibhav"] , index =['p','r','s','q','t'])
s3

p     Akshit
r     Madhav
s      Kedar
q       Ajay
t    Vaibhav
dtype: object

In [20]:
s3["p"]

'Akshit'

In [22]:
s3["p":"s"]

p    Akshit
r    Madhav
s     Kedar
dtype: object

In [25]:
names = ["Akshit" , "Madhav", "Kedar" ,"Ajay" ,"Vaibhav"]
s4=pd.Series(names)
s4

0     Akshit
1     Madhav
2      Kedar
3       Ajay
4    Vaibhav
dtype: object

In [26]:
s4[0:3]

0    Akshit
1    Madhav
2     Kedar
dtype: object

In [28]:
s3.index

RangeIndex(start=0, stop=5, step=1)

In [29]:
s4.index

RangeIndex(start=0, stop=5, step=1)

In [33]:
s3[s3=="Madhav"]

1    Madhav
dtype: object

In [39]:
s3=="Akshit"

0     True
1    False
2    False
3    False
4    False
dtype: bool

In [40]:
d={'a':1,'b':2,'c':3,'d':4,'e':5}
s3=pd.Series(d)
s3

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [41]:
s1

0    p
1    r
2    s
3    q
4    t
dtype: object

In [44]:
s4=s1.append(s2)
s4

C:\Users\madha\AppData\Local\Temp\ipykernel_6636\2562205657.py:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  s4=s1.append(s2)


0    p
1    r
2    s
3    q
4    t
1    p
2    r
3    s
3    q
3    t
dtype: object

In [48]:
ser1=pd.Series([100,20,10,150,60],index=["india","nepal","china","japan","korea"])
ser2=pd.Series([100,20,90,10,1],index=["india","america","japan","korea","Russia"])
ser1

india    100
nepal     20
china     10
japan    150
korea     60
dtype: int64

In [46]:
ser2

india    100
nepal     20
china     10
japan    150
korea     60
dtype: int64

In [50]:
ser1+ser2

Russia       NaN
america      NaN
china        NaN
india      200.0
japan      240.0
korea       70.0
nepal        NaN
dtype: float64

In [52]:
print("Median",ser1.median())
print("Max",ser1.max())
print("Min",ser1.min())

Median 60.0
Max 150
Min 10


In [71]:
import numpy as np
arr=np.random.randn(6,4)
print(arr)

[[ 0.27597991  0.14890664 -0.11146113 -1.53782954]
 [-1.52590464 -1.63852526 -0.72649512 -0.18544695]
 [ 1.60372684  0.83956506  0.8512606   0.6283045 ]
 [-0.43077557  1.20777135 -0.97218219 -1.26796941]
 [ 0.26737406  0.16338237 -0.56445008  0.29924141]
 [ 0.43065872 -0.24472663 -0.77017572  1.04930034]]


In [59]:
arr1=np.random.randint(24,size=(6,4))
arr1

array([[ 5, 23, 16, 14],
       [17, 21, 13,  0],
       [20, 11, 18, 15],
       [20, 10, 10,  2],
       [11,  6, 22, 21],
       [15,  0,  9, 15]])

In [65]:
row=['A','B','c','D','E','F']
column=['1','2','3','4']
df=pd.DataFrame(arr1,index=row,columns=column)
df

1   2   3   4
A   5  23  16  14
B  17  21  13   0
c  20  11  18  15
D  20  10  10   2
E  11   6  22  21
F  15   0   9  15

In [72]:
row=['A','B','c','D','E','F']
column=['1','2','3','4']
df2=pd.DataFrame(arr,index=row,columns=column)
df2

1         2         3         4
A  0.275980  0.148907 -0.111461 -1.537830
B -1.525905 -1.638525 -0.726495 -0.185447
c  1.603727  0.839565  0.851261  0.628304
D -0.430776  1.207771 -0.972182 -1.267969
E  0.267374  0.163382 -0.564450  0.299241
F  0.430659 -0.244727 -0.770176  1.049300

In [73]:
df.tail(2)

1  2   3   4
E  11  6  22  21
F  15  0   9  15

In [74]:
df.describe()

1          2          3          4
count   6.000000   6.000000   6.000000   6.000000
mean   14.666667  11.833333  14.666667  11.166667
std     5.819507   8.795832   4.966555   8.280499
min     5.000000   0.000000   9.000000   0.000000
25%    12.000000   7.000000  10.750000   5.000000
50%    16.000000  10.500000  14.500000  14.500000
75%    19.250000  18.500000  17.500000  15.000000
max    20.000000  23.000000  22.000000  21.000000

In [76]:
df2.describe()

1         2         3         4
count  6.000000  6.000000  6.000000  6.000000
mean   0.103510  0.079396 -0.382251 -0.169067
std    1.034865  0.991895  0.670087  1.041240
min   -1.525905 -1.638525 -0.972182 -1.537830
25%   -0.256238 -0.146318 -0.759256 -0.997339
50%    0.271677  0.156145 -0.645473  0.056897
75%    0.391989  0.670519 -0.224708  0.546039
max    1.603727  1.207771  0.851261  1.049300

In [79]:
summ=df.describe(include='all')
type(summ)


pandas.core.frame.DataFrame

In [81]:
df.to_excel("randomDataFrame.xlsx")
df.to_csv("randomDataFrame.csv")

In [90]:
df.isnull().sum()
df2.isnull().sum()
df


1   2   3   4
A   5  23  16  14
B  17  21  13   0
c  20  11  18  15
D  20  10  10   2
E  11   6  22  21
F  15   0   9  15

In [87]:
df.isnull().any()

1    False
2    False
3    False
4    False
dtype: bool

In [92]:
df.isnull().all()

1    False
2    False
3    False
4    False
dtype: bool

In [94]:
import pandas as pd
studentData = {
    'name' : ['jack', 'Riti', 'Aadi','Bhavna'],
    'age' : ["?", 30, "?",32],
    'salary':[10000,150298,75000,200000],
    'city' : ['Sydney',"Delhi", 'New york','Maryland']

}
rowlabel=['A','B','C','D']
studentData

{'name': ['jack', 'Riti', 'Aadi', 'Bhavna'],
 'age': ['?', 30, '?', 32],
 'salary': [10000, 150298, 75000, 200000],
 'city': ['Sydney', 'Delhi', 'New york', 'Maryland']}

In [95]:
df1=pd.DataFrame(studentData,index=rowlabel)
df1

name age  salary      city
A    jack   ?   10000    Sydney
B    Riti  30  150298     Delhi
C    Aadi   ?   75000  New york
D  Bhavna  32  200000  Maryland